- include_vars: ../../../vars.yml

- name: Do an apt-get update & upgrade
  raw: sudo apt-get -y update && sudo apt-get -y upgrade

- name: 'install python2'
  raw: sudo apt-get -y install python-minimal
  changed_when: false

- name: Install required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
    - git

- name: Set the hostname
  become: yes
  hostname:
    name: "{{ hostname }}"

- name: Add vpn to host file
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ vpn_gateway }} vpn"
    state: present

- name: Install bind9
  become: yes
  package:
    name: bind9
    state: present

- name: Copy bind9 conf to file system
  become: yes
  template:
    src: bind9.j2
    dest: /etc/bind/named.conf.options

